# Generated by Django 5.2.3 on 2025-06-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "roll_number",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("address", models.TextField(max_length=100)),
                ("phone_number", models.PositiveIntegerField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
    ]
