# Generated by Django 5.2.3 on 2025-06-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.PositiveIntegerField(),
        ),
    ]
